### ISSUE TITLE
[edrawmax] Chineese translation UTF 8

### ISSUE THREAD

**Issue by thegayankalinga** [alerque/aur#1]
Can't translate pathname 'opt/EdrawMax-9/help_de/ContextHelp/images/sharevialink - 副本.png' to UTF-8

**Comment by alerque** [comment]
I'm not the current maintainer of this any more nor am I updating my fork that was to fix the broken AUR package. There seems to be a new maintainer on the official [AUR package](https://aur.archlinux.org/packages/edrawmax) though so there is some hope that the language issues were fixed in updates since this issue was current. Please comment there if this is still a problem. If perchance it is still broken or the default language isn't fixed lets file an orphan request and I'd be happy to pick it up and maintain it, in which case we can re-open this issue.
