### ISSUE TITLE
xiphos falls over with error loading (missing) shared library libicui18n.so.68

### ISSUE THREAD

**Issue by egeiro** [alerque/aur#16]
Hi Caleb,

My version of xiphos from your repo falls over with an error:

`xiphos: error while loading shared libraries: libicui18n.so.68: cannot open shared object file: No such file or directory`

I did a full upgrade yesterday (#pacman -Syu) and it looks like the upgrade for package icu has caused the problem. I tried downgrading icu from 69.1-1 back to 68.2-1 but it has dependencies of a number of other packages.

Regards, Gary

**Comment by alerque** [comment]
Thank you for the report (again). I see the ICU dependency was entered incorrectly, it was using it without having called it out specifically. I'm going to fix this by version locking it to the system ICU version. What that's going to do is help pacman throw a warning *before* it breaks rather than after. The next time you do a full system upgrade and ICU updates it's going to throw an error saying Xiphos needs whatever one is was compiled against. That should error on my machine too so I know it needs rebuilding. I did see ICU come through the other day and bumped several other packages I knew needed it, but this one wasn't on my radar. Unfortunately this process of triggering a rebuild for the repository is not automatic. I update at least some of my systems almost every day, but feel free to ping if you see it behind.

This should be resolved by xiphos-4.2.1-5 which is uploading as I type this.

**Comment by egeiro** [comment]
All good here. Thanks Caleb.
