### ISSUE TITLE
Defcon build failures (and other requirements)

### ISSUE THREAD

**Issue by djmattyg007** [alerque/aur#17]
This package fails to build in a clean chroot because of missing makedeps.

Please see my comments here:

https://aur.archlinux.org/packages/python-defcon

**Comment by alerque** [comment]
Thanks for the alert. This is actually an upstream bug, their source packages are broken. The entire point of python-setuptools-scm is that only Git (SCM based!) sources should need that dependency, once you release the project using the sources builds the SCM related tooling is removed and the resulting source package can be built with regular tools.

It seems the upstream in this case has uploaded a raw Git archive tarball instead of an actual source build. I've [reported this upstream](https://github.com/robotools/defcon/issues/354) and will post a temporary work around for 0.8.1 builds now.
