### ISSUE TITLE
package `tor-browser` in your repo out of date

### ISSUE THREAD

**Issue by dreirund** [alerque/aur#18]
`yay -Ss 'tor-browser' | grep -E '/tor-browser[[:space:]]' | awk '{print $1" "$2}'`:  
```
aur/tor-browser 10.0.16-1
chaotic-aur/tor-browser 10.0.16-1
alerque/tor-browser 9.5-1
```

(Haven't checked for other packages.)

Can you implement a routine of updating packages in your repo asap, or drop them out of your repo otherwise?

Thanks for maintaining!

**Comment by alerque** [comment]
I just updated `tor-browser`, thanks for the poke.

Tor is a tricky one for me to keep up to date because the sources are frequently blocked in the country where my tooling for generating packages and signing them is located.

You may want to tweak the order of repositories you load so that fallback order goes community packages take priority, then next whatever repo is most "fresh", then whatever has packages that the others don't.

Largely because I'm signing and hand checking almost everything I build I can't promise my repo will always be the freshest (although it isn't too far off for most packages). Some people have wired up automatic builds that just keep everything up to date, but that is usually at the expense of not manually reviewing builds or having meaningful package signing.

**Comment by dreirund** [comment]
*On Wed, 05 May 2021 09:55:08 -0700, ***@***.***> wrote about "Re: [alerque/aur] package `tor-browser` in your repo out of date (#18)":*

> Largely because I'm signing and hand checking almost everything I
> build I can't promise my repo will always be the freshest (although
> it isn't too far off for most packages). Some people have wired up
> automatic builds that just keep everything up to date, but that is
> usually at the expense of not manually reviewing builds or having
> meaningful package signing.

Thanks alot for the explanation!!


-- 
Erleuchtung, die:
  Wenn Du plötzlich merkst, dass Du sie gar nicht brauchst.
  (Janosch.)

Enlightenment:
  When you suddenly realise that you do not need it.
  (Janosch.)
