### ISSUE TITLE
Gitahead

### ISSUE THREAD

**Issue by FabioLolix** [alerque/aur#30]
https://aur.archlinux.org/packages/gitahead/#comment-836200

Hello Caleb, I worked on a gitahead pkgbuild too (since a lot of months now) and would like share with you, git submodules are configured

https://github.com/FabioLolix/PKGBUILD-AUR_fix/blob/master/g/gitahead/PKGBUILD
https://github.com/FabioLolix/PKGBUILD-AUR_fix/tree/master/g/gitahead

last version no longer builds due to no longer existing submodule git commit

**Comment by alerque** [comment]
Thanks for the reference. I actually posted a working build a couple hours ago before I saw this which has some overlap -- but also some differences. I don't understand why people are complaining about the non-existant git commit however, I don't have a problem cloning the submodules as saved in the tagged Gitahead release. In any case I would like to rework the sources to just download the tarball(s) of relevant sources. We also need to setup vendoring because there is no reason to use some of the bundled libraries in a build like this. After that, the build still needs some cleanup. The package function especially is a mess, I don't think that's the right cmake incantation at all.

Happy to accept PR's for incremental improvements from the current state...

**Comment by alerque** [comment]
I'm going to close this issue since I don't think it is actionable any more. We both worked on Gitahead packaging, but the project is no longer being developed and I think we've both switched to Gittyup, including my stable and your VCS packaging of same.
