### ISSUE TITLE
font dependencies cleanup leftovers

### ISSUE THREAD

**Issue by prettyv** [alerque/aur#7]
First, thanks a lot for taking care of so many font- and typography-related packages, much appreciated!

While tracking the recent font dependencies cleanup I noticed that one of the fonts I have installed from your unofficial repo - ```ttf-courier-prime``` - still depends on fontconfig. I see you've been tracking that cleanup early yourself, thanks for that. The corresponding package seems to be missing here however, probably because it has a different AUR maintainer. Should I disregard this specific package from your repo or if not could you update it accordingly? It seems similar applies for ```ttf-gentium-basic``` as well.

Also, since you understandably don't publish all the ```*-ib{,x}``` packages listed here anymore I thought I'd mention that you still have ```otf-erewhon-{ibx,infinality}``` in the repos, I assume these are unneeded by now.

**Comment by alerque** [comment]
Thanks for bringing this up. There is definitely a long tail of font packages that still need cleanup.

* The maintainer for `ttf-courier-prime` just updated the package today, and I rebuilt so it should be dependency free now when installed from my repository. I also got notifications turned on so I hopefully won't miss updates on it in the future when the AUR package gets bumped.

* For `ttf-gentium-basic` the maintainer has not been responding to requests to fix this. I've applied to have the package orphaned. As soon as that goes through or it gets updated I'll rebuild the package in my repo. I *could* of course fix it myself and send out a package anyway, but I'm a little reluctant to put packages in the repo that do not match the sources in the AUR because it causes version confusion. Hopefully this package will be resolved one way or another soon. I'll leave this open to track that resolution.

* Honestly I don't know what to do about `*-ib{,x}` packages yet. I started working through when converting them to split packages so they wouldn't duplicate the work of the same fonts in normal variants, but that is slow going because it requires merge approval in the AUR for every package and some maintainers are resistant to change. At the same time I started getting the feeling like nobody is actually using infinality any more and I'm considering whether to campaign to have ALL the infinality stuff removed entirely. See #8 for a new issue tracking this.

**Comment by alerque** [comment]
The `ttf-gentium-basic` package finally got orphaned last week. I adopted it and fixed the outstanding issues in 6bb003e published as `1.1-5`.

The Infinality issues are tracked in a different issue, so I'm closing this one as all actionable bits are complete.
